services:
  wordpress:
    labels:
      caddy: ${PROJECT_URL:-${PROJECT_NAME}.localhost}
      caddy.reverse_proxy: "{{upstreams 80}}"
    networks:
      - default
      - proxy
    ports: !reset []
networks:
  default:
    name: ${PROJECT_NAME}-network
  proxy:
    name: ${PROXY_NETWORK}
    external: true
